spring.application.name=spring_spotify


server.servlet.context-path=/spotify

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/spotify
spring.jpa.hibernate.ddl-auto=update
spring.datasource.username=root
spring.datasource.password=123456

flyway.baselineOnMigrate=true

jwt.signerKey = "xzvurD1MHyeFXTQiS/Uq1o0QlAtXsXD17aaoE/e8BWZRDduuiO2zZHQPDu68VeVa"
jwt.validity-in-days = 10

anb52.upload-file.base-uri=file:///D:/WorkSpace/Code/Spring/uploadSpotify/

# Gi?i h?n kích th??c t?p t?i ?a
spring.servlet.multipart.max-file-size=100MB

# Gi?i h?n kích th??c toàn b? yêu c?u t?i lên (bao g?m c? các t?p và thông tin khác trong form)
spring.servlet.multipart.max-request-size=100MB

###
#config email with gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=lean2k4@gmail.com
spring.mail.password=ehmjnbbwlituwqij
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#
###